/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package query.genome;

import org.junit.Test;

public class AppTest {
	@Test
	public void testAppHasAGreeting() {
		CliRunner classUnderTest = new CliRunner();
		// assertNotNull("app should have a greeting", classUnderTest.getGreeting());
	}
}
